//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySqlDataBuild.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MySqlDataBuild.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 #if SERVER
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Data;
        ///using System.Diagnostics;
        ///using System.Text;
        ///using System.Threading;
        ///using System.IO;
        ///using {USING};
        ///using Net.Event;
        ///using Net.System;
        ///using Net.Share;
        ///using System.Collections.Concurrent;
        ///using Cysharp.Threading.Tasks;
        ///
        ///{NAMESPACE_BEGIN}
        ///    /// &lt;summary&gt;
        ///    /// {DBNAME}数据库管理类
        ///    /// 此类由MySqlDataBuild工具生成, 请不要在此类编辑代码! 请新建一个类文件进行分写
        ///    /// &lt;para&gt;MySqlDataBuild工具提供Rpc自动同步到mysql数据库的功能, 提供数据库注释功能&lt;/para&gt;
        ///    /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string databaseTemplate {
            get {
                return ResourceManager.GetString("databaseTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] MySql_6_x_x {
            get {
                object obj = ResourceManager.GetObject("MySql_6_x_x", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] MySql_8_x_x {
            get {
                object obj = ResourceManager.GetObject("MySql_8_x_x", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Data;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using Net.Share;
        ///using Net.Event;
        ///#if SERVER
        ///using Net.System;
        ///using Cysharp.Threading.Tasks;
        ///using {USING};
        ///#endif
        ///using BooleanObs = Net.Common.PropertyObserverAuto&lt;bool&gt;;
        ///using ByteObs = Net.Common.PropertyObserverAuto&lt;byte&gt;;
        ///using SByteObs = Net.Common.PropertyObserverAuto&lt;sbyte&gt;;
        ///using Int16Obs = Net.Common.PropertyObserverAuto&lt;short&gt;;
        ///using UInt16Obs = Net.Common.PropertyObserverAuto&lt;ushort&gt;;
        ///using Ch [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string tableTemplate {
            get {
                return ResourceManager.GetString("tableTemplate", resourceCulture);
            }
        }
    }
}
